# Utilise une image Node.js officielle
FROM node:16-alpine

# Définit le répertoire de travail
WORKDIR /usr/src/app

# Copie les fichiers nécessaires pour le backend
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Expose le port 3000
EXPOSE 3000

# Commande pour démarrer le serveur
CMD ["npm", "start"]